<?php

namespace Database\Seeders;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Carbon\Carbon;

class ProductSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
    DB::table('products')->insert([
        [
        'name' => 'Flower Anggrek Bulan',
        'category_id'=>1,
        'image' => 'storage/img/sample-product.jpg',
        'description' => 'Wangi segar dengan sensasi manis diakhir saat telon sudah terkena kulit. Seperti aroma kesegaran hujan dengan harum manis dari bunga anggrek.',
        'price' => 55500,
        'stock' => 50,
        'rating' => 5,
        'weight' => 1,
        'slug' => 'flower-anggrek-bulan',
        'discount_id' => 1,
        'created_at' => Carbon::now(),
        'updated_at' => Carbon::now()
    ],
    [
        'name' => 'Flower Magnolia',
        'category_id'=>1,
        'image' => 'storage/img/sample-product.jpg',
        'description' => 'Wangi calming. Aroma menenangkan yang lembut, Telon Habbie mencoba mereplikasi suasana tenang melalui aroma magnolia.',
        'price' => 55500,
        'stock' => 50,
        'rating' => 5,
        'weight' => 1,
        'slug' => 'flower-magnolia',
        'discount_id' => null,
        'created_at' => Carbon::now(),
        'updated_at' => Carbon::now()
    ],
    [
        'name' => 'Flower Peony',
        'category_id'=>1,
        'image' => 'storage/img/sample-product.jpg',
        'description' => 'Perpaduan aroma lembut, manis, asam dan adanya hint pahit sehingga memberi kesan aroma everlasting yang tidak membosankan.',
        'price' => 55500,
        'stock' => 50,
        'rating' => 4,
        'weight' => 1,
        'slug' => 'flower-peony',
        'discount_id' => null,
        'created_at' => Carbon::now(),
        'updated_at' => Carbon::now()
    ],
    [
        'name' => 'Flower Tulip',
        'category_id'=>1,
        'image' => 'storage/img/sample-product.jpg',
        'description' => 'Aroma yang menggambarkan keunikan dari aroma bunga tulip yang segar.',
        'price' => 55500,
        'stock' => 50,
        'rating' => 5,
        'weight' => 1,
        'slug' => 'flower-tulip',
        'discount_id' => null,
        'created_at' => Carbon::now(),
        'updated_at' => Carbon::now()
    ],
    [
        'name' => 'Flower Lotus',
        'category_id'=>1,
        'image' => 'storage/img/sample-product.jpg',
        'description' => "Wangi yang memberikan sensasi kesegaran dan kelembutan. Aroma lotus memiliki kesan 'semangat' sehingga cocok digunakan sehari-hari.",
        'price' => 55500,
        'stock' => 50,
        'rating' => 4,
        'weight' => 1,
        'slug' => 'flower-lotus',
        'discount_id' => null,
        'created_at' => Carbon::now(),
        'updated_at' => Carbon::now()
    ],
    [
        'name' => 'Flower Petunia',
        'category_id'=>1,
        'image' => 'storage/img/sample-product.jpg',
        'description' => 'Wangi dengan karakter manis yang kuat dengan tambahan aroma asam diakhir. Wanginya memberi sensasi dingin ke segar saat dihirup oleh hidung.',
        'price' => 55500,
        'stock' => 50,
        'rating' => 5,
        'weight' => 1,
        'slug' => 'flower-petunia',
        'discount_id' => null,
        'created_at' => Carbon::now(),
        'updated_at' => Carbon::now()
    ],
    [
        'name' => 'Flower Sakura',
        'category_id'=>1,
        'image' => 'storage/img/sample-product.jpg',
        'description' => 'Menggambarkan sensasi aroma musim semi dari negara Jepang. Wangi lembut dengan sensasi manis dan fresh ditambah ada sedikit aroma pahit di akhir saat sudah meresap ke kulit.',
        'price' => 55500,
        'stock' => 50,
        'rating' => 4,
        'weight' => 1,
        'slug' => 'flower-sakura',
        'discount_id' => null,
        'created_at' => Carbon::now(),
        'updated_at' => Carbon::now()
    ],
    [
        'name' => 'Flower Cactus',
        'category_id'=>1,
        'image' => 'storage/img/sample-product.jpg',
        'description' => 'Wangi yang segar dengan campuran aroma manis unik yang jarang dijumpai di Telon Flower Series.',
        'price' => 55500,
        'stock' => 50,
        'rating' => 4,
        'weight' => 1,
        'slug' => 'flower-cactus',
        'discount_id' => null,
        'created_at' => Carbon::now(),
        'updated_at' => Carbon::now()
    ],
    [
        'name' => 'Flower Pansy',
        'category_id'=>1,
        'image' => 'storage/img/sample-product.jpg',
        'description' => 'Wangi manis dari bunga pansy dengan campuran sensasi sedikit pahit dan asam yang segar eksotis. Memberikan wangi yang akan diingat siapapun yang mencium aroma telon ini.',
        'price' => 55500,
        'stock' => 50,
        'rating' => 4,
        'weight' => 1,
        'slug' => 'flower-pansy',
        'discount_id' => null,
        'created_at' => Carbon::now(),
        'updated_at' => Carbon::now()
    ],
    [
        'name' => 'Flower Fuchsia',
        'category_id'=>1,
        'image' => 'storage/img/sample-product.jpg',
        'description' => 'Wangi manis bunga dengan tambahan sensasi asam dan pahit ditambah ada kesan powdery.',
        'price' => 55500,
        'stock' => 50,
        'rating' => 4,
        'weight' => 1,
        'slug' => 'flower-fuchsia',
        'discount_id' => null,
        'created_at' => Carbon::now(),
        'updated_at' => Carbon::now()
    ],
    [
        'name' => 'Flower Rose',
        'category_id'=>1,
        'image' => 'storage/img/sample-product.jpg',
        'description' => 'Wangi khas bunga mawar dipadukan dengan wangi asam yang segar dan ringan.',
        'price' => 55500,
        'stock' => 50,
        'rating' => 4,
        'weight' => 1,
        'slug' => 'flower-rose',
        'discount_id' => null,
        'created_at' => Carbon::now(),
        'updated_at' => Carbon::now()
    ],
    [
        'name' => 'Flower Lily',
        'category_id'=>1,
        'image' => 'storage/img/sample-product.jpg',
        'description' => 'Wangi segar yang lembut, ditambah saat terkena kulit memberikan sensasi manis.',
        'price' => 55500,
        'stock' => 50,
        'rating' => 4,
        'weight' => 1,
        'slug' => 'flower-lily',
        'discount_id' => null,
        'created_at' => Carbon::now(),
        'updated_at' => Carbon::now()
    ],
    [
        'name' => 'Flower Granium',
        'category_id'=>1,
        'image' => 'storage/img/sample-product.jpg',
        'description' => 'Perpaduan wangi manis gardenia dengan sedikit wangi pahit dan asam yang fresh. Menampilkan wangi elegan yang eksotis.',
        'price' => 55500,
        'stock' => 50,
        'rating' => 4,
        'weight' => 1,
        'slug' => 'flower-granium',
        'discount_id' => null,
        'created_at' => Carbon::now(),
        'updated_at' => Carbon::now()
    ],
    [
        'name' => 'Gardenia',
        'category_id'=>1,
        'image' => 'storage/img/sample-product.jpg',
        'description' => 'Wangi yang memberikan kelembutan dan harum yang manis khas aroma bunga gardenia yang jarang kita temui.',
        'price' => 55500,
        'stock' => 50,
        'rating' => 4,
        'weight' => 1,
        'slug' => 'flower-gardenia',
        'discount_id' => null,
        'created_at' => Carbon::now(),
        'updated_at' => Carbon::now()
    ],
    [
        'name' => 'Flower Lemon',
        'category_id'=>1,
        'image' => 'storage/img/sample-product.jpg',
        'description' => 'Kesegaran wangi citrus dipadukan sedikit wangi pahit dan asam dari bunga jeruk.',
        'price' => 55500,
        'stock' => 50,
        'rating' => 4,
        'weight' => 1,
        'slug' => 'flower-lemon',
        'discount_id' => null,
        'created_at' => Carbon::now(),
        'updated_at' => Carbon::now()
    ],
    [
        'name' => 'Tea Jasmine',
        'category_id'=>2,
        'image' => 'storage/img/sample-product.jpg',
        'description' => 'Wangi harum bunga melati yang manis, dipadukan dengan aroma menenangkan dari wangi teh yang sedikit pahit.',
        'price' => 55500,
        'stock' => 50,
        'rating' => 4,
        'weight' => 1,
        'slug' => 'tea-jasmine',
        'discount_id' => null,
        'created_at' => Carbon::now(),
        'updated_at' => Carbon::now()
    ],
    [
        'name' => 'Tea Fresh',
        'category_id'=>2,
        'image' => 'storage/img/sample-product.jpg',
        'description' => 'Wangi unik dari dua kuncup daun teh termuda. Memberikan efek kesegaran dari teh khas Brazil.',
        'price' => 55500,
        'stock' => 50,
        'rating' => 4,
        'weight' => 1,
        'slug' => 'tea-fresh',
        'discount_id' => null,
        'created_at' => Carbon::now(),
        'updated_at' => Carbon::now()
    ],
    [
        'name' => 'Tea Matcha',
        'category_id'=>2,
        'image' => 'storage/img/sample-product.jpg',
        'description' => 'Keharuman teh hijau yang menenangkan dengan sedikit sentuhan aroma pahit khas teh, memberikan sensasi rileks sejak terhirup oleh hidung.',
        'price' => 55500,
        'stock' => 50,
        'rating' => 4,
        'weight' => 1,
        'slug' => 'tea-matcha',
        'discount_id' => null,
        'created_at' => Carbon::now(),
        'updated_at' => Carbon::now()
    ],
    [
        'name' => 'Tea White',
        'category_id'=>2,
        'image' => 'storage/img/sample-product.jpg',
        'description' => 'Wangi teh yang lembut dengan sedikit sensasi manis yang menyegarkan.',
        'price' => 55500,
        'stock' => 50,
        'rating' => 4,
        'weight' => 1,
        'slug' => 'tea-white',
        'discount_id' => null,
        'created_at' => Carbon::now(),
        'updated_at' => Carbon::now()
    ],
    [
        'name' => 'Tea Green Honey',
        'category_id'=>2,
        'image' => 'storage/img/sample-product.jpg',
        'description' => 'Wangi teh yang sedikit pahit menenangkan memberikan sensasi yang lembut dengan tanbahan sensasi manis diakhir.',
        'price' => 55500,
        'stock' => 50,
        'rating' => 4,
        'weight' => 1,
        'slug' => 'tea-green-honey',
        'discount_id' => null,
        'created_at' => Carbon::now(),
        'updated_at' => Carbon::now()
    ],
    [
        'name' => 'Tea Black',
        'category_id'=>2,
        'image' => 'storage/img/sample-product.jpg',
        'description' => 'Aroma menenangkan dari seduhan teh. Memberikan wangi yang lembut dan menenangkan dengan sedikit sensasi asam dan pahit.',
        'price' => 55500,
        'stock' => 50,
        'rating' => 4,
        'weight' => 1,
        'slug' => 'tea-black',
        'discount_id' => null,
        'created_at' => Carbon::now(),
        'updated_at' => Carbon::now()
    ],
    [
        'name' => 'Tea Oolong',
        'category_id'=>2,
        'image' => 'storage/img/sample-product.jpg',
        'description' => 'Wangi teh yang lembut yang manis dengan memadukan kesan creamy dan sedikit aroma fruity diakhir.',
        'price' => 55500,
        'stock' => 50,
        'rating' => 4,
        'weight' => 1,
        'slug' => 'tea-oolong',
        'discount_id' => null,
        'created_at' => Carbon::now(),
        'updated_at' => Carbon::now()
    ],
    [
        'name' => 'Tea Pu-erh',
        'category_id'=>2,
        'image' => 'storage/img/sample-product.jpg',
        'description' => 'Aroma teh yang lembut dengan karakter yang cenderung silky dan adanya hint floral.',
        'price' => 55500,
        'stock' => 50,
        'rating' => 4,
        'weight' => 1,
        'slug' => 'tea-pu-erh',
        'discount_id' => null,
        'created_at' => Carbon::now(),
        'updated_at' => Carbon::now()
    ],
    [
        'name' => 'Tea Yellow',
        'category_id'=>2,
        'image' => 'storage/img/sample-product.jpg',
        'description' => 'Sensasi perpaduan wangi teh yang menenangkan dengan sedikit aroma buah citrus diakhir.',
        'price' => 55500,
        'stock' => 50,
        'rating' => 4,
        'weight' => 1,
        'slug' => 'tea-yellow',
        'discount_id' => null,
        'created_at' => Carbon::now(),
        'updated_at' => Carbon::now()
    ],
    [
        'name' => 'Tea Tree',
        'category_id'=>2,
        'image' => 'storage/img/sample-product.jpg',
        'description' => 'Perpaduan wangi seperti aroma kayu putih dan kayu manis sehinggal menampilkan wangi yang terkesan bright.',
        'price' => 55500,
        'stock' => 50,
        'rating' => 4,
        'weight' => 1,
        'slug' => 'tea-tree',
        'discount_id' => null,
        'created_at' => Carbon::now(),
        'updated_at' => Carbon::now()
    ],
    [
        'name' => 'Tea Bouquet',
        'category_id'=>2,
        'image' => 'storage/img/sample-product.jpg',
        'description' => 'Aroma teh hitam yang kuat berpadu dengan wangi melati dan mawar yang manis dan menenangkan.',
        'price' => 55500,
        'stock' => 50,
        'rating' => 4,
        'weight' => 1,
        'slug' => 'tea-bouquet',
        'discount_id' => null,
        'created_at' => Carbon::now(),
        'updated_at' => Carbon::now()
    ],
    [
        'name' => 'Tea Darjeeling',
        'category_id'=>2,
        'image' => 'storage/img/sample-product.jpg',
        'description' => 'Gabungan dari aroma Mustacel yang manis dengan aroma pahit yang musky.',
        'price' => 55500,
        'stock' => 50,
        'rating' => 4,
        'weight' => 1,
        'slug' => 'tea-darjeeling',
        'discount_id' => null,
        'created_at' => Carbon::now(),
        'updated_at' => Carbon::now()
    ],
    [
        'name' => 'Tea Earl Grey',
        'category_id'=>2,
        'image' => 'storage/img/sample-product.jpg',
        'description' => 'Wangi bergamot dengan karakter citrus yang dominan menghasilkan wangi teh yang unik menyegarkan.',
        'price' => 55500,
        'stock' => 50,
        'rating' => 4,
        'weight' => 1,
        'slug' => 'tea-earl-grey',
        'discount_id' => null,
        'created_at' => Carbon::now(),
        'updated_at' => Carbon::now()
    ],
    [
        'name' => 'Tea Sencha',
        'category_id'=>2,
        'image' => 'storage/img/sample-product.jpg',
        'description' => 'Aroma flavorfull yang ada pada teh hijau saat dipetik di musim dingin menghasilkan wangi rileks yang lembut dan manis.',
        'price' => 55500,
        'stock' => 50,
        'rating' => 4,
        'weight' => 1,
        'slug' => 'tea-sencha',
        'discount_id' => null,
        'created_at' => Carbon::now(),
        'updated_at' => Carbon::now()
    ],
    [
        'name' => 'Tea Masala',
        'category_id'=>2,
        'image' => 'storage/img/sample-product.jpg',
        'description' => 'Perpaduan wangi unik teh yang rileks dan lembut dipadukan dengan karakter wangi rempah (jahe, kapulaga, dan kayu manis) menghasilkan wangi yang kompleks dengan intensitas mild.',
        'price' => 55500,
        'stock' => 50,
        'rating' => 4,
        'weight' => 1,
        'slug' => 'tea-masala',
        'discount_id' => null,
        'created_at' => Carbon::now(),
        'updated_at' => Carbon::now()
    ],
    [
        'name' => 'Turkish Saffron',
        'category_id'=>3,
        'image' => 'storage/img/sample-product.jpg',
        'description' => '',
        'price' => 65000,
        'stock' => 50,
        'rating' => 4,
        'weight' => 1,
        'slug' => 'turkish-saffron',
        'discount_id' => null,
        'created_at' => Carbon::now(),
        'updated_at' => Carbon::now()
    ],
    [
        'name' => 'Afgan Saffron',
        'category_id'=>3,
        'image' => 'storage/img/sample-product.jpg',
        'description' => '',
        'price' => 65000,
        'stock' => 50,
        'rating' => 4,
        'weight' => 1,
        'slug' => 'afgan-saffron',
        'discount_id' => null,
        'created_at' => Carbon::now(),
        'updated_at' => Carbon::now()
    ],
    [
        'name' => 'Spanish Saffron',
        'category_id'=>3,
        'image' => 'storage/img/sample-product.jpg',
        'description' => '',
        'price' => 65000,
        'stock' => 50,
        'rating' => 4,
        'weight' => 1,
        'slug' => 'spanish-saffron',
        'discount_id' => null,
        'created_at' => Carbon::now(),
        'updated_at' => Carbon::now()
    ],
    [
        'name' => 'Negin Saffron',
        'category_id'=>3,
        'image' => 'storage/img/sample-product.jpg',
        'description' => '',
        'price' => 65000,
        'stock' => 50,
        'rating' => 4,
        'weight' => 1,
        'slug' => 'negin-saffron',
        'discount_id' => null,
        'created_at' => Carbon::now(),
        'updated_at' => Carbon::now()
    ],
    [
        'name' => 'Khasmir Saffron',
        'category_id'=>3,
        'image' => 'storage/img/sample-product.jpg',
        'description' => '',
        'price' => 65000,
        'stock' => 50,
        'rating' => 4,
        'weight' => 1,
        'slug' => 'khasmir-saffron',
        'discount_id' => null,
        'created_at' => Carbon::now(),
        'updated_at' => Carbon::now()
    ],
    [
        'name' => 'Iran Saffron',
        'category_id'=>3,
        'image' => 'storage/img/sample-product.jpg',
        'description' => '',
        'price' => 65000,
        'stock' => 50,
        'rating' => 4,
        'weight' => 1,
        'slug' => 'iran-saffron',
        'discount_id' => null,
        'created_at' => Carbon::now(),
        'updated_at' => Carbon::now()
    ],
    [
        'name' => 'Turkish Vanilla',
        'category_id'=>4,
        'image' => 'storage/img/sample-product.jpg',
        'description' => '',
        'price' => 65000,
        'stock' => 50,
        'rating' => 4,
        'weight' => 1,
        'slug' => 'turkish-vanilla',
        'discount_id' => null,
        'created_at' => Carbon::now(),
        'updated_at' => Carbon::now()
    ],
    [
        'name' => 'China Vanilla',
        'category_id'=>4,
        'image' => 'storage/img/sample-product.jpg',
        'description' => '',
        'price' => 65000,
        'stock' => 50,
        'rating' => 4,
        'weight' => 1,
        'slug' => 'china-vanilla',
        'discount_id' => null,
        'created_at' => Carbon::now(),
        'updated_at' => Carbon::now()
    ],
    [
        'name' => 'Mexican Vanilla',
        'category_id'=>4,
        'image' => 'storage/img/sample-product.jpg',
        'description' => '',
        'price' => 65000,
        'stock' => 50,
        'rating' => 4,
        'weight' => 1,
        'slug' => 'mexican-vanilla',
        'discount_id' => null,
        'created_at' => Carbon::now(),
        'updated_at' => Carbon::now()
    ],
    [
        'name' => 'Madagascar Vanilla',
        'category_id'=>4,
        'image' => 'storage/img/sample-product.jpg',
        'description' => '',
        'price' => 65000,
        'stock' => 50,
        'rating' => 4,
        'weight' => 1,
        'slug' => 'madagascar-vanilla',
        'discount_id' => null,
        'created_at' => Carbon::now(),
        'updated_at' => Carbon::now()
    ],
    [
        'name' => 'american vanilla',
        'category_id'=>4,
        'image' => 'storage/img/sample-product.jpg',
        'description' => '',
        'price' => 65000,
        'stock' => 50,
        'rating' => 4,
        'weight' => 1,
        'slug' => 'american-vanilla',
        'discount_id' => null,
        'created_at' => Carbon::now(),
        'updated_at' => Carbon::now()
    ],
    [
        'name' => 'Indonesian Vanilla',
        'category_id'=>4,
        'image' => 'storage/img/sample-product.jpg',
        'description' => '',
        'price' => 65000,
        'stock' => 50,
        'rating' => 4,
        'weight' => 1,
        'slug' => 'indonesian-vanilla',
        'discount_id' => 2,
        'created_at' => Carbon::now(),
        'updated_at' => Carbon::now()
    ],
    ]);
    }
}
